### ISSUE TITLE
How to load .dymo files

### ISSUE THREAD

**Issue by RicardoViteriR** [jack-carling/dymo-connect#1]
hello, is this library able to open .dymo files?

**Comment by jack-carling** [comment]
Hi! There's no functionality of the library to open `.dymo` files at the moment. However, they're basically XML files so if you're running the package from a node backend you can use the native File System module.

```javascript
const Dymo = require('dymo-connect')
const fs = require('fs')

const data = fs.readFileSync('./path/to/file.dymo', 'utf-8')
Dymo.printLabel('Your LabelWriter', data)
```

If you're solely doing it in a frontend application I would look into the FileReader of the File API
https://developer.mozilla.org/en-US/docs/Web/API/FileReader

Edit: closing this as won't fix for now since the two methods vary depending on if you use the library in a frontend or backend.

**Comment by RicardoViteriR** [comment]
Hi @jack-carling, I was testing some XMLs that I copied from a .dymo file. The printer did not print anything. Here is the sample QR XML https://gist.github.com/RicardoViteriR/1cee0f795c8f446c2d2320f3eed24d80 wondering what may be wrong.

**Comment by jack-carling** [comment]
Do you have the software installed? DYMO Connect for mac / windows is required for the printing to work since the package calls the web SDK. You can download it from Dymo's official website.
https://www.dymo.com/support?cfid=user-guide

I see no issues with your xml, I was able to use the `renderLabel()` method, so I doubt there would be an issue printing it.

![](https://github.com/jack-carling/dymo-connect/assets/72305598/52aba2ba-c744-4c8b-8f9c-3b2ddbb0f0ca)

**Comment by RicardoViteriR** [comment]
Hmm I will try again. I got it to work by implementing the javascript sdk placing it in the script tags.

**Comment by RicardoViteriR** [comment]
Yes the service is running. I am doing a browser implementation so I’ll try again.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
